- name: Kill previous instance
  hosts: localhost
  connection: local

  tasks:
    - name: Include vars
      include_vars: secret.yml

    - name: Kill previous instance
      ec2_instance:
        aws_access_key: "{{access_key}}"
        aws_secret_key: "{{secret_key}}"
        security_token: "{{session_token}}"
        state: absent
        filters:
          tag:purpose: eshop
